// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5exLN8YfRiShtHrlQi4E0S5CGKl3bInY',
    appId: '1:159746824681:web:38f842216228aebf661378',
    messagingSenderId: '159746824681',
    projectId: 'flutter-4fdb8',
    authDomain: 'flutter-4fdb8.firebaseapp.com',
    storageBucket: 'flutter-4fdb8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvKy2Yt96rDyzRXcVCdyviMqS1lU8S5bw',
    appId: '1:159746824681:android:3d6667dcbb81fe4a661378',
    messagingSenderId: '159746824681',
    projectId: 'flutter-4fdb8',
    storageBucket: 'flutter-4fdb8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBB930T6coDE2ffkLxKCAji9NF747yjGs4',
    appId: '1:159746824681:ios:bda021da2cfaa9ef661378',
    messagingSenderId: '159746824681',
    projectId: 'flutter-4fdb8',
    storageBucket: 'flutter-4fdb8.appspot.com',
    iosClientId: '159746824681-ou6rrme1eeo48i5tkge43dtq1ibbv9ok.apps.googleusercontent.com',
    iosBundleId: 'com.example.firstApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBB930T6coDE2ffkLxKCAji9NF747yjGs4',
    appId: '1:159746824681:ios:668f4342efaa46b4661378',
    messagingSenderId: '159746824681',
    projectId: 'flutter-4fdb8',
    storageBucket: 'flutter-4fdb8.appspot.com',
    iosClientId: '159746824681-63amuoudecs66j37m5a46fdkqpd85v52.apps.googleusercontent.com',
    iosBundleId: 'com.example.firstApp.RunnerTests',
  );
}
